version: '3.8'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik-proxy-controller"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    name: traefik-proxy
